---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.3.0
_src_path: https://github.com/quickplates/meta
description: Generic project template 👤
projectname: generic
username: quickplates
