# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.0
_src_path: gh:quickplates/meta
accountname: quickplates
description: Generic project template 👤
example: true
examplerepo: quickplates/generic-example
reponame: generic
repourl: https://github.com/quickplates/generic
type: generic
