---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.1
_src_path: https://github.com/quickplates/meta
description: Generic project template 👤
project_name: generic
repository: https://github.com/quickplates/generic
username: quickplates
