# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.5.2
_src_path: gh:quickplates/meta
accountname: quickplates
description: Generic project template 👤
example: true
exampleaccountname: quickplates
exampledescription: Generic project example 👤
examplereponame: generic-example
reponame: generic
repourl: https://github.com/quickplates/generic
type: generic
